"""initial_schema

Revision ID: dd8663f04c43
Revises: 
Create Date: 2026-04-27 21:50:04.902813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8663f04c43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('eid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('e_type', sa.String(), nullable=True),
    sa.Column('e_name', sa.String(), nullable=True),
    sa.Column('manual', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('eid')
    )
    op.create_table('lab_member',
    sa.Column('mid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('type', sa.Enum('student', 'collaborator', 'faculty', name='membertype'), nullable=False),
    sa.Column('mentor', sa.Integer(), nullable=True),
    sa.Column('m_sdate', sa.Date(), nullable=True),
    sa.Column('m_edate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mentor'], ['lab_member.mid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('publication',
    sa.Column('pubid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pubid')
    )
    op.create_table('collaborator',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('cv', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['lab_member.mid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('device',
    sa.Column('did', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('p_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['eid'], ['equipment.eid'], ),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('faculty',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['lab_member.mid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('project',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('s_date', sa.Date(), nullable=True),
    sa.Column('e_date', sa.Date(), nullable=True),
    sa.Column('e_duration', sa.String(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leader'], ['lab_member.mid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('publishes',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('pubid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mid'], ['lab_member.mid'], ),
    sa.ForeignKeyConstraint(['pubid'], ['publication.pubid'], ),
    sa.PrimaryKeyConstraint('mid', 'pubid')
    )
    op.create_table('student',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['lab_member.mid'], ),
    sa.PrimaryKeyConstraint('mid'),
    sa.UniqueConstraint('sid')
    )
    op.create_table('grant',
    sa.Column('gid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_duration', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('budget', sa.Numeric(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['project.pid'], ),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('uses',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('did', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('s_date', sa.Date(), nullable=True),
    sa.Column('e_date', sa.Date(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['did'], ['device.did'], ),
    sa.ForeignKeyConstraint(['eid'], ['equipment.eid'], ),
    sa.ForeignKeyConstraint(['mid'], ['lab_member.mid'], ),
    sa.PrimaryKeyConstraint('mid', 'did', 'eid')
    )
    op.create_table('works',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['lab_member.mid'], ),
    sa.ForeignKeyConstraint(['pid'], ['project.pid'], ),
    sa.PrimaryKeyConstraint('pid', 'mid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('uses')
    op.drop_table('grant')
    op.drop_table('student')
    op.drop_table('publishes')
    op.drop_table('project')
    op.drop_table('faculty')
    op.drop_table('device')
    op.drop_table('collaborator')
    op.drop_table('publication')
    op.drop_table('lab_member')
    op.drop_table('equipment')
    sa.Enum('student', 'collaborator', 'faculty', name='membertype').drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###